### ISSUE TITLE
There has been a critical error on this website — after guttenberg upgrade

### ISSUE THREAD

**Issue by mrlosh** [mjh-nyc/mjh-education#15]
https://staging-education.mjhnyc.org/

**Comment by asierrajr** [comment]
Fixed
https://staging-education.mjhnyc.org/

Count function error, variable needs to be checked

**Comment by mrlosh** [comment]
Has this been deployed? please deploy if not

**Comment by asierrajr** [comment]
Deployed to production

**Comment by allenkyee** [comment]
closing this...client reported no further issue
