### ISSUE TITLE
Disable site registration

### ISSUE THREAD

**Issue by asierrajr** [mjh-nyc/mjh-education#16]
Disable site registration, end users who sign up to get lesson plans do not need accounts anymore.

Check all places where users can register and update signup links in code

**Comment by asierrajr** [comment]
Set to draft https://staging-education.mjhnyc.org/register/
Set to draft https://staging-education.mjhnyc.org/login/
Set to draft https://staging-education.mjhnyc.org/my-account/

Created Signup page (https://staging-education.mjhnyc.org/signup/) and updated links.
I only saw links to sign up on the individual lesson plan page

**Comment by allenkyee** [comment]
closing this
