### ISSUE TITLE
Create form to access lesson plans

### ISSUE THREAD

**Issue by asierrajr** [mjh-nyc/mjh-education#17]
Create a form to access lesson plans

Email
Name
Zip
School name 
(captcha)

On submission

- Store entry as a post type using acf for the additional fields
- Set cookie to allow users access to lessons

**Comment by asierrajr** [comment]
This has been implemented and can be viewed here

https://staging-education.mjhnyc.org/signup/

On submit, it sends data to mailchimp #18 and sets a cookie to access #19 

Ideally you arrive to this page from a lesson plan like:

https://staging-education.mjhnyc.org/lessons/lesson-plan-on-antisemitism/

Click on signup and it will send you to the form.
Once you submit form, it will redirect you back to the lesson plan page.

There is no link to get to this page directly.

**Comment by allenkyee** [comment]
Not working.
https://staging-education.mjhnyc.org/lessons/lesson-plan-on-antisemitism/
Clicked on Signup
Filled out the info and threw me back to the form again.

Let's QA this on zoom

**Comment by allenkyee** [comment]
Tried multiple email accounts, some already in teh system and some not in Mail Chimp and still bounces me back to form

**Comment by allenkyee** [comment]
tried multiple times

**Comment by asierrajr** [comment]
The issue was the API call I was using was only attempting to update an existing account and failing.
Had to write up an api call to check if email exists in mailchimp, if no, insert, if yes, update

Up on staging

**Comment by asierrajr** [comment]
Also made the math captcha easier

**Comment by allenkyee** [comment]
going to close this and enter individual issue tickets. thanks
