### ISSUE TITLE
Lesson Plan Access

### ISSUE THREAD

**Issue by asierrajr** [mjh-nyc/mjh-education#19]
Since there is no login state for accessing lesson plans, need to update php code to check for a cookie instead of login-state 

If cookie is present, allow access to lesson plan
If not, require end user to fill out access form #17

**Comment by asierrajr** [comment]
Cookie called `mjhedu_signed_up` is set when a end user signs up.
Cookie is good for a year.

You can kill that cookie via developer tool or use incognito mode to test

Up on staging

**Comment by allenkyee** [comment]
cookie seems to work, I will continuously test
