### ISSUE TITLE
Export form submissions

### ISSUE THREAD

**Issue by asierrajr** [mjh-nyc/mjh-education#20]
The plan is to store this as a custom post type

Allow admin to export this data

We are already have this plugin set up 
https://wordpress.org/plugins/wp-all-export/

We can setup a WP_QUERY export, which is free, to export the post type with a custom meta key/meta value

Example from existing Advanced Form module

```
'post_type' => 'af_entry', 'meta_key' => 'entry_form','meta_value' => 'form_5bf57489bfcf1'
```

**Comment by allenkyee** [comment]
It isn't clear how the admin is downloading the users...if it's not clear to me, it won't be for the client.

Is it "Users"?  We're going to need to set this up better.

![image](https://github.com/mjh-nyc/mjh-education/assets/11357734/d3243440-e9cc-405f-ad43-56d888c400d0)

**Comment by asierrajr** [comment]
Sorry, I didn't submit my comment

There are 2 ways to view submissions

For a list of submissions via the Wordpress UX:

https://staging-education.mjhnyc.org/wp/wp-admin/edit.php?post_type=af_entry

The form name is Signup Access

---

For exporting
Navigate here: https://staging-education.mjhnyc.org/wp/wp-admin/admin.php?page=pmxe-admin-manage

Click on Run Report on the Signup Access Submissions exporter that I created.

The users are for user accounts in Wordpress and does not apply here.

**Comment by allenkyee** [comment]
thanks, got it and looks good. keeping this open

**Comment by allenkyee** [comment]
tested on production, it works, although very slow on my connection possiblty
