### ISSUE TITLE
Advanced Form Plugin

### ISSUE THREAD

**Issue by asierrajr** [mjh-nyc/mjh-education#21]
We have the free version of this plugin installed, though I am not sure if we are using it anymore since the education site piggy backs the main site for contact information, etc....

The free version uses honeypot for spam filtering and I may piggy back this plugin since it saves submission entries and I can export them already.

The pro version of this plugin allows for 

1. Recaptcha
2. Mailchimp integration

https://hookturn.io/downloads/advanced-forms-pro/

---

Alternate solutions

We can install this plugin which has a google recaptcha field I can setup via ACF Pro
https://www.acf-extended.com/

Mailchimp:
I can hook into the submissions and send the data via php code using the API, but I'll need to custom write this with hooks.

Please evaluate

**Comment by allenkyee** [comment]
If we get the developer, we can use on any number of sites? I say if it saves you even 1-2 hours of work, then it is worth getting. @mrlosh, can you evaluate?

**Comment by asierrajr** [comment]
Decided not to pay for this since we never use this plugin for other projects or we have other solutions like Contact Form 7 or Formiddable. 

I implement my own math captcha, very basic but it works

**Comment by asierrajr** [comment]
I also implemented custom code via a form hook to mailchimp

**Comment by asierrajr** [comment]
I decided not to use google captcha due to the overhead that brings in and adding a big plugin that extends acf pro seemed a bit overkill
