### ISSUE TITLE
Sendgrid

### ISSUE THREAD

**Issue by asierrajr** [mjh-nyc/mjh-education#22]
Setup SMTP using https://wpmailsmtp.com/ with integration with Sendgird

We will need access to their sendgrid account and somehow access their DNS record for domain validation

https://wpmailsmtp.com/docs/how-to-set-up-the-sendgrid-mailer-in-wp-mail-smtp/

Who is contact point at the Museum?

**Comment by allenkyee** [comment]
mroodberg@mjhnyc.org / Madeleine

**Comment by allenkyee** [comment]
Josh at MJH said he did the records and I see the page changed. Can you verify?

**Comment by asierrajr** [comment]
Checked via the web applications, it says the SPF record is there and I see the DKIM and SPF in the email headers.

It did complain about DMARC missing, is this correct?
It's just a record that should be added in the DNS.

https://wpmailsmtp.com/how-to-create-dmarc-record/

**Comment by asierrajr** [comment]
This has been setup on production

**Comment by allenkyee** [comment]
closing, tested password retrival on both sites and did a test email from the plugin on both sites
