### ISSUE TITLE
disabling registration until new work is launched

### ISSUE THREAD

**Issue by allenkyee** [mjh-nyc/mjh-education#24]
client would like to know if we can disable registration altogether until the new work is launched.

**Comment by asierrajr** [comment]
We can set the register page to draft, but what do we do with the button links that ask user to sign up?

**Comment by allenkyee** [comment]
how about we create a username and password, just add it as a note, people can login with that

**Comment by asierrajr** [comment]
Not following.
People would still be able to login, we just kill registration.
Registration on MJH EDU is custom built and is a page

**Comment by allenkyee** [comment]
we are close to done, let's get it out
