### ISSUE TITLE
Download all link

### ISSUE THREAD

**Issue by allenkyee** [mjh-nyc/mjh-education#27]
https://education.mjhnyc.org/lessons/lesson-plan-one-introduction-to-jewish-life-during-the-holocaust/
https://staging-education.mjhnyc.org/lessons/lesson-plan-one-introduction-to-jewish-life-during-the-holocaust/

Staging doesn't have the Download All Lesson Plans link. Will our work over right this?

**Comment by asierrajr** [comment]
Good Catch

Alter the check for the Download All link

Up on staging

**Comment by allenkyee** [comment]
i see it now
