### ISSUE TITLE
After signing up, need confirmation message and link

### ISSUE THREAD

**Issue by allenkyee** [mjh-nyc/mjh-education#28]
Just in case anyone is passing around this link (https://education.mjhnyc.org/signup/) and they didn't select a lesson plan before, the user will be orphaned and presented with a blank screen

![image](https://github.com/mjh-nyc/mjh-education/assets/11357734/d1ac0cf8-703c-4788-87bf-63e85cf5f162)

Can you put in HTML textfield so we can put in text and link so user can get back to https://education.mjhnyc.org ?

We can also lose the intro text on sign up page. I put that in there because I know they will want to add some text there.

**Comment by asierrajr** [comment]
In the form settings, there is a success message text area you can add. 
It's under the display tab found here
https://staging-education.mjhnyc.org/wp/wp-admin/post.php?post=7828&action=edit

**Comment by allenkyee** [comment]
I added text to this and don't see either before the form and after submit

![image](https://github.com/mjh-nyc/mjh-education/assets/11357734/de392c05-9ef5-44b8-b044-f87da2cd25ac)

**Comment by allenkyee** [comment]
cleared site cache, no difference

**Comment by asierrajr** [comment]
The success message only appears when the page is redirect back to the signup page.
When you have a lesson plan redirect, it doesn't go to this page.
<img width="1473" alt="Screen Shot 2023-09-29 at 12 35 04 PM" src="https://github.com/mjh-nyc/mjh-education/assets/429930/5ae5be6e-942a-44f1-b406-bec5d137f918">

**Comment by allenkyee** [comment]
is there an easy way to add text before email field? I'm just anticipaiting they will want to message.

If I add it to the body in Wordpress, it displays on the final screen.

**Comment by asierrajr** [comment]
Copy should go in the Signup Wordpress post

https://staging-education.mjhnyc.org/wp/wp-admin/post.php?post=7826&action=edit

**Comment by allenkyee** [comment]
ok closing this
