### ISSUE TITLE
getting 404 on the lesson plan zips and download all lesson plans

### ISSUE THREAD

**Issue by allenkyee** [mjh-nyc/mjh-education#30]
![image](https://github.com/mjh-nyc/mjh-education/assets/11357734/59f43006-843b-40ca-9a37-96112f66d2cf)

Was able to download it yesterday

**Comment by asierrajr** [comment]
It's the setup for the WP Offload we have for staging.
When I copy down the database from production, I preserve the production links but i have to remove the cloudfront url so we can test uploads to the staging buck.

The above is linked to the production s3 bucket, which I purposely block so everything is served via cloudfront domain

**Comment by allenkyee** [comment]
ok, going to keep this open so i check when we go live

**Comment by allenkyee** [comment]
lesson plans downloading ok, downloaded both
